### ISSUE TITLE
[Suggestion]Setting up Discussion tab

### ISSUE THREAD

**Issue by gogog01-29-2021** [mannmi/KoreanWonDetection#6]
How about set up discussion tab so we can discuss small issues in discussion tab and Organize the result to Issue tab?

![setupdiscussiontab1](https://github.com/user-attachments/assets/bc33114b-693c-44f4-846a-e28529256c16)
![setupdiscussiontab2](https://github.com/user-attachments/assets/a20de501-52f5-4fa3-a787-9e422226fcc4)

**Comment by mannmi** [comment]
It has been implemented the issue is that the template is not yet working.
If you know why then i would apreciate the support :)

**Comment by mannmi** [comment]
Sorry that i forgot to update the Thread with the update :) If you know how to fix the issue with the template not loading for the issue discusion tab then please create a pull request with the Feature. 

Kind Regards,
Mannmi
